name: VNC with Xfce and Xvfb

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install VNC, Xvfb, and Xfce
      run: |
        sudo apt-get update
        sudo apt-get install -y x11vnc xvfb xfce4 xfce4-terminal dbus-x11

    - name: Download and auth ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz
        tar -xf ngrok-v3-stable-linux-amd64.tgz
        ./ngrok authtoken YOUR_NGROK_AUTH_TOKEN_HERE

    - name: Start Xvfb and VNC server
      run: |
        /usr/bin/Xvfb :99 -screen 0 1024x768x24 &
        sleep 3
        x11vnc -display :99 -forever -notls -shared -viewonly &
        ./ngrok tcp 5900
